title: "Soosiana"
description: "Hungarian Malacological Journal"

baseurl: https://soosiana.github.io

include: [".htaccess"]
exclude: ["README.md", "LICENSE.md"]
timezone: America/Edmonton

encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

author: "Hungarian Malacology Society (MAMAT)"

#categories: ["Etc", "Talks", "Papers", "Code", "Tutorials"]

gems:
  - jekyll-feed
  - jekyll-sitemap
